import { useMemo, useState } from 'react'
import { GOOGLE_CALENDAR_SCOPE, validateGoogleCalendarConfig } from '../../lib/googleCalendar'

type CalendarOption = { id: string; summary: string; accessRole?: string }
type Props = { clientId: string; redirectUri: string; calendarId: string; proposalCalendarId?: string; connected: boolean; calendars: CalendarOption[]; busy?: boolean; error?: string; onSave: (value: { clientId: string; redirectUri: string; calendarId: string; proposalCalendarId?: string }) => void; onConnect: () => void; onDisconnect: () => void; onTestRead: () => Promise<number> }

export function GoogleSetupWizard({ clientId, redirectUri, calendarId, proposalCalendarId = '', connected, calendars, busy, error: externalError, onSave, onConnect, onDisconnect, onTestRead }: Props) {
  const [draft, setDraft] = useState({ clientId, redirectUri, calendarId, proposalCalendarId })
  const [step, setStep] = useState(1)
  const error = useMemo(() => { try { validateGoogleCalendarConfig({ ...draft, scopes: [GOOGLE_CALENDAR_SCOPE] }); return '' } catch (value) { return value instanceof Error ? value.message : 'Configuration incomplete.' } }, [draft])
  return <section className="settings-card setup-wizard"><span className="eyebrow">GOOGLE CALENDAR SETUP · STEP {step}/4</span><h3>{['Google Cloud', 'Connect account', 'Select calendars', 'Verify'][step - 1]}</h3>{step === 1 && <><p className="settings-note">Create the OAuth client using the exact origins in <code>docs/google-calendar-setup.md</code>. Never enter a Google password or client secret here.</p><label>Public OAuth client ID<input value={draft.clientId} onChange={(event) => setDraft({ ...draft, clientId: event.target.value.trim() })} placeholder="…apps.googleusercontent.com" /></label><label>App URL<input value={draft.redirectUri} onChange={(event) => setDraft({ ...draft, redirectUri: event.target.value.trim() })} /></label><button className="quiet-button" onClick={() => onSave(draft)}>Save public configuration</button></>}{step === 2 && <><p className="settings-note">Google Identity Services handles the password and consent. Family Planner receives a short-lived scoped access token in memory.</p><button className="primary-button" disabled={busy || !draft.clientId} onClick={connected ? onDisconnect : onConnect}>{busy ? 'Connecting…' : connected ? 'Disconnect Google' : 'Connect Google Calendar'}</button></>}{step === 3 && <><p className="settings-note">Select the dedicated shared calendar and optional proposal-inbox calendar. Family Planner never guesses by name.</p><label>Authoritative shared calendar<select value={draft.calendarId} onChange={(event) => { const value = { ...draft, calendarId: event.target.value }; setDraft(value); onSave(value) }}><option value="">Select a calendar</option>{calendars.map((calendar) => <option value={calendar.id} key={calendar.id}>{calendar.summary} ({calendar.accessRole})</option>)}</select></label><label>Proposal inbox calendar<select value={draft.proposalCalendarId} onChange={(event) => { const value = { ...draft, proposalCalendarId: event.target.value }; setDraft(value); onSave(value) }}><option value="">None / file import only</option>{calendars.filter((calendar) => calendar.id !== draft.calendarId).map((calendar) => <option value={calendar.id} key={calendar.id}>{calendar.summary}</option>)}</select></label></>}{step === 4 && <><p className="settings-note">Test read access with synthetic data before any write test. A marked write must always require separate confirmation.</p><button className="primary-button" disabled={!connected || !draft.calendarId} onClick={async () => { const count = await onTestRead(); alert(`Read test succeeded: ${count} event(s) in the next 7 days.`) }}>Test calendar read</button></>}{(externalError || error) && <p className="setup-error">{externalError || error}</p>}<div className="wizard-actions"><button className="quiet-button" disabled={step === 1} onClick={() => setStep(step - 1)}>Back</button><button className="quiet-button" disabled={step === 4} onClick={() => setStep(step + 1)}>Next</button></div></section>
}
