services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.36.5
    restart: unless-stopped
    command: ["serve", "--http=0.0.0.0:8090"]
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
